"""
Django settings for FlightsFromStoryAndFestivali project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '2q-c16*zcbctolw_q%by-c_(%7oh6uloq188p4*f-n0a-ic^ez'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True 

ALLOWED_HOSTS = ["api.FlightsFromStoryAndFestival.io"]

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_swagger',
    'corsheaders',
#    'authentication',
#    'metrics',
#    'logs',
    'alerts',
    'stories',
    'festivals',
)

MIDDLEWARE_CLASSES = (
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'FlightsFromStoryAndFestival.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'FlightsFromStoryAndFestival.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Swagger Documentation Setting
SWAGGER_SETTINGS = {
    'info': {
        'description': 'Click below to see the documentation',
        'title': 'API Documentation for FlightsFromStoryAndFestival',
    },
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# CORS SETTINGS
CORS_ORIGIN_ALLOW_ALL = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

# FlightsFromStoryAndFestival_API specific settings

# Authentication
AUTHENTICATION_SERVER = 'http://10.0.0.39:3000'
TOKEN_PATH = '/oauth/token'
USER_PATH = '/api/user'
PROJECT_TOKEN_PATH = '/api/filters'
AUTH_CLIENT_ID = 'FlightsFromStoryAndFestival'
AUTH_CLIENT_SECRET = 'ilovedata'

# KafkaServer - For tests it should not be the production one
KAFKA_SERVER = '10.0.0.6:9092'
KAFKA_LOG_TOPIC = 'FlightsFromStoryAndFestival_logs'
KAFKA_METRIC_TOPIC = 'FlightsFromStoryAndFestival_metrics'

#Inflxudb
#change it to internal ip before production
INFLUXDB_LB_HOST = '10.0.0.73'
INFLUXDB_LB_PORT = '8086'
INFLUXDB_LB_USER = 'root'
INFLUXDB_LB_PW   = 'root'

# Elasticsearch
ELASTICSEARCH_SERVER = '10.0.0.37'

#Hackathon allowed tokens
ALLOWED_TOKENS = ["7e97dd28","28edde36","d10c1ff1","68c5e168","af79d0e1","38e4640a","83d4f028","db524f5d","4ba11349","a2c13a9a","53726bee","ac9b7312","236258b2","d536a8fd","2eebdeaa","ce56e090","87a97221","635afe05","31952706","b4083616","0f73cbbe","d8eeb2e4","3518f415","c58fbba5","348d1d2b","add09776","9bea930a","2d848a81","b7590ac5","95fe3f5c","3b247512","069d50d4","04c45f41","f2573eda","b8b06b9d","9a8d8d1b","8b5a5777","20eedb68","91264cbf","dfdb64c7","c04ec31c","e84118a3","0b0a7445","f43a71a5","1254cec4","c7a2f8ee","e3db74b2","5f71615c","f30163a0","fd46bb82","3bdcf353","c2818ae3","864444d8","a7b71e4b","8d94a705","1c42ec90","a093c292","8069a6e6","991df93d","25354d48","0aa86fd5","b8c7c7ea","ae1e745a","a36e9237","a2f85a9b","8cbaf2fc","dfd060f5",

"9a6b90ba" , "8f8e1a68" , "84868eea" , "5865ec35" , "3281e45d" , "471985eb" , "a28f8d4f" , "5cf99026" , "4568e8e9" , "eb44bd6d" , "a56233bc" , "e0b05922" , "91ec7af8" , "a80ffc10" , "ae7929c0" , "e92deb2b" , "7da289f5" , "3b45e87a" , "d1b11210" , "059fb087" , "8e5779ce" , "0d10aee6" , "ce80b25b" , "ea755001" , "7b3f1a35" , "a5ed32f5" , "abcfb76c" , "83390535" , "7773b37f" , "6083b500" , "a1275db7" , "8fac88c6" , "b2a44384" , "ff236cb5" , "35314e22" , "cc0e7d6b" , "c05f230e" , "f4e1fd1d" , "41bc840e" , "246ac83a" , "1a712896" , "3deb78d3" , "e8af9816" , "102655e5" , "7a0f58a8" , "82ed015e" , "5010f7af" , "b8a42b8a" , "22a2f5d6" , "5eaf7408" , "8c8456af" , "a7e4f4a6" , "c0a7b6fc" , "07390c2b" , "8b51edf3" , "ad8b5e91" , "c6cde871" , "99df46b7" , "7d6ebee1" , "27b3eb38" , "f34ca7e0" , "97bb9e9a" , "a285ffef" , "d9c007e8" , "16b58868" , "0dbe7e47" , "9b4b952f" , "9a80c5f3" , "e92ccf55" , "1477a2af" , "0094779c" , "56456d21" , "4ce5d1c2" , "b5f6e6b4" , "e0f77a9e" , "46977092" , "22dfb1fb" , "9d020aef" , "51f5a031" , "bcbbb34e" , "82e5e5ca" , "b7c1b7d8" , "91a340e4" , "088d2323" , "19806f04" , "2f586ba2" , "d125e636" , "c6cbb50a" , "994f23a7" , "da569726" , "44e57612" , "58807e5b" , "9cee1b6b" , "7804bc91" , "636f4d20" , "42663650" , "4813e66e" , "f03e4eac" , "50a07b31" , "56c224ca" , "b5811723" , "6480a884" , "1836fc3b" , "71d1a09d" , "30184997" , "f0069791" , "207ecb6a" , "b68dc99a" , "8c4378c9" , "5e9acf6f" , "e64e9b1b" , "2c4f84f4" , "aaaa69d2" , "a5903d67" , "50bed3bc" , "6d604821" , "83dea053" , "6f679635" , "5fd6f35f" , "6dce55d8" , "17f0c00c" , "4d5f8db5" , "c7b73440" , "47061a77" , "d48733dc" , "b014d20a" , "8581f3c2" , "12d14a50" , "f9e0b787" , "679b7f75" , "53d91378" , "9c29b6be" , "4250c65d" , "5ec18f4e" , "e8618594" , "b76ee3a2" , "484e8a1d" , "acc58aa0" , "f6345812" , "797b20dc" , "b140726a" , "22d4fa8d" , "6c29bfcb" , "2c031704" , "63e188c3" , "05d37505" , "ecc3e424" , "2b60317a" , "00ba024d" , "5267ea12" , "6531a876" , "42f2234a" , "8ca5f6c1" , "5b80b364" , "07074fc2" , "b69fcfa3" , "54b12e25" , "1256fd24" , "0812a0f5" , "3c8cbc66" , "9cefd37c" , "bc3664d4" , "89bff059" , "f19adc65" , "0ed0c5f8" , "0f1a974c" , "92caae21" , "062526f9" , "582685bc" , "ebe76dc1" , "48c6bb08" , "d42ead6e" , "0bdf8f06" , "5e97c9f6" , "af867c1d" , "091c8416" , "e4961ec0" , "cd468047" , "52b1d2ee" , "5d411012" , "46da3cf1" , "0212a249" , "c0551c29" , "2e54e7dc" , "c0359cab" , "bb19f066" , "69bfc606" , "b68c98c2" , "330e593c" , "59fec385" , "0a1d5239" , "e34925d3" , "e3c958b8" , "87b7b43c" , "05d139c1" , "6ac282da" , "a8604c92" , "170da7fb" , "ed39b55e" , "4563117a"]
